# Этап 1: Сборка React приложения
FROM node:20-slim AS build

WORKDIR /app

# Копируем только файлы зависимостей для кеширования
COPY package*.json ./
RUN npm install

# Копируем остальной код и собираем проект
COPY . .
RUN npm run build

# Этап 2: Запуск Nginx
FROM nginx:stable-alpine

# Копируем ваш кастомный конфиг Nginx (тот самый со /api/)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Копируем собранный билд из первого этапа в папку Nginx
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
