FROM nginx:alpine
# Copy frontend from dir (frontend/)
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copy dist from dir (frontend/dist/)
COPY ./dist/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
